<a href="https://colab.research.google.com/github/ibacaraujo/deep-learning-wizard/blob/master/matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrices with PyTorch

In [1]:
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [2]:
import numpy as np
np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

In [4]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [5]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [6]:
np.random.rand(2, 2)

array([[0.76626252, 0.09962916],
       [0.65028105, 0.43951075]])

In [7]:
torch.rand(2, 2)

tensor([[0.6229, 0.2683],
        [0.4214, 0.6805]])

In [8]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [10]:
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [11]:
torch.rand(2, 2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [0]:
np_array = np.ones((2, 2))

In [14]:
# bridge
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [15]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [16]:
# CPU to GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
torch_tensor.to(device)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [17]:
device

device(type='cpu')

In [18]:
# resizing tensors
a = torch.ones((2, 2))
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [19]:
print(a.size())

torch.Size([2, 2])


In [20]:
a.view(4)

tensor([1., 1., 1., 1.])

In [21]:
a.view(4).size()

torch.Size([4])

In [23]:
# addition
a = torch.ones(2, 2)
b = torch.ones(2, 2)
a.add_(b)
print(a)

tensor([[2., 2.],
        [2., 2.]])
